### ISSUE TITLE
优化 SCSS 文件并添加暗色模式支持

### ISSUE THREAD

**Issue by RainyDreams** [RainyDreams/rs2024a#1]
### 优化 SCSS 文件并添加暗色模式支持

**描述**

为了提高项目的可维护性和性能，需要对 SCSS 文件进行优化，并添加对暗色模式的支持。优化内容包括变量和混合的使用、代码复用、压缩和清理无用代码等。

**优化目标**

1. **变量和混合**：
   - 创建一个 `_variables.scss` 文件，定义所有的颜色、字体、间距等全局变量。
   - 创建一个 `_mixins.scss` 文件，定义常用的 SCSS 混合（Mixin）。

2. **代码复用**：
   - 提取重复的样式到混合或占位符选择器中。
   - 删除不必要的重复代码。

3. **文件结构**：
   - 按照功能或组件将 SCSS 文件进行模块化管理。
   - 创建一个 `main.scss` 文件，导入所有的 SCSS 子文件。

4. **压缩和清理**：
   - 使用工具对 SCSS 进行压缩，减少文件大小。
   - 清理无用的样式和代码。

5. **支持暗色模式**：
   - 定义暗色模式的颜色变量。
   - 根据用户的系统偏好或手动切换来应用暗色模式的样式。

**步骤**

1. **创建变量和混合文件**：
   - 在 `src/styles` 目录下创建 `_variables.scss` 和 `_mixins.scss` 文件。
   - 在 `_variables.scss` 文件中定义项目中的常用变量。
   - 在 `_mixins.scss` 文件中定义常用的混合。

2. **优化现有 SCSS 文件**：
   - 使用 `_variables.scss` 中定义的变量替换硬编码的颜色、字体等。
   - 使用 `_mixins.scss` 中的混合替换重复的样式。

3. **重构文件结构**：
   - 将现有的 SCSS 文件按照功能或组件进行模块化管理。
   - 创建 `main.scss` 文件，导入所有的 SCSS 子文件。

4. **压缩和清理**：
   - 使用 Webpack 或其他构建工具对 SCSS 进行压缩。
   - 清理无用的样式和代码。

5. **添加暗色模式支持**：
   - 在 `_variables.scss` 文件中添加暗色模式的颜色变量。
   - 在全局样式文件中添加媒体查询，根据用户系统的暗色模式偏好应用相应的样式。
   - 提供手动切换暗色模式的功能。

**示例代码**

```scss
// src/styles/_variables.scss
$primary-color: #3498db;
$secondary-color: #2ecc71;
$font-family: 'Helvetica, Arial, sans-serif';
$spacing-unit: 16px;

// Light mode colors
$background-color-light: #ffffff;
$text-color-light: #000000;

// Dark mode colors
$background-color-dark: #121212;
$text-color-dark: #ffffff;

// src/styles/_mixins.scss
@mixin center-flex {
  display: flex;
  justify-content: center;
  align-items: center;
}

// src/styles/main.scss
@import 'variables';
@import 'mixins';
@import 'components/button';
@import 'layouts/header';
@import 'layouts/footer';

body {
  background-color: $background-color-light;
  color: $text-color-light;

  @media (prefers-color-scheme: dark) {
    background-color: $background-color-dark;
    color: $text-color-dark;
  }
}
```

**任务列表**

- [ ] 创建 `_variables.scss` 文件
- [ ] 创建 `_mixins.scss` 文件
- [ ] 优化现有 SCSS 文件
- [ ] 重构文件结构
- [ ] 压缩和清理 SCSS 文件
- [ ] 添加暗色模式支持
